// GENERATED by scripts/build-menu-facts.mjs — do not edit by hand.
//
// Facts the menu renderer needs but cannot look up at render time: it runs in a
// Deno edge function with no filesystem and no access to the app's repo.
// Regenerate with:  node scripts/build-menu-facts.mjs

// Real pixel dimensions of every menu photo, measured from the files. Emitted as
// width/height so the browser can reserve layout space before the image decodes.
export const PHOTO_DIMS = {
 "assets/menu-photos/achari-chicken.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/apollo-fish.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/badam-ki-kheer.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/beef-bihari-roll.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/beef-boti-roll.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/beef-chapli-kabab.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/beef-frontier-rice.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/beef-seekh-kabab.jpg": [
  1090,
  1200
 ],
 "assets/menu-photos/beef-sheekh-kabab-roll.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/bhendi-masala.jpg": [
  1200,
  783
 ],
 "assets/menu-photos/bihari-kabab.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/butter-chicken.jpg": [
  896,
  1200
 ],
 "assets/menu-photos/butter-naan.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/butter-paneer.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chapati.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-65-rice.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-65-roll-naan.jpg": [
  1200,
  732
 ],
 "assets/menu-photos/chicken-65.jpg": [
  1200,
  1200
 ],
 "assets/menu-photos/chicken-boti-roll.jpg": [
  965,
  1200
 ],
 "assets/menu-photos/chicken-boti.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-chapli-kabab.jpg": [
  1200,
  895
 ],
 "assets/menu-photos/chicken-dum-biryani.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-malai-boti-roll.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-malai-boti.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-manchurian.jpg": [
  1200,
  872
 ],
 "assets/menu-photos/chicken-pakora.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/chicken-seekh-kabab-roll.jpg": [
  1200,
  1154
 ],
 "assets/menu-photos/chicken-seekh-kabab.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/chicken-tandoori-full.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/chicken-tandoori-half.jpg": [
  830,
  1200
 ],
 "assets/menu-photos/chicken-tikka-masala.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/chicken-tikka.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/chili-chicken-rice.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/chilli-chicken.jpg": [
  883,
  1200
 ],
 "assets/menu-photos/daal-tadka.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/double-ka-meeta.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/dum-ka-chicken.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/dum-ka-gosht.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/fish-pakora.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/fried-fish.jpg": [
  1200,
  862
 ],
 "assets/menu-photos/fries.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/frontier-chicken.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/garlic-naan.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/goat-biryani.jpg": [
  900,
  1200
 ],
 "assets/menu-photos/goat-khorma.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/golden-shaahi-platter.jpg": [
  826,
  1200
 ],
 "assets/menu-photos/gulab-jamun.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/haleem.jpg": [
  1183,
  1200
 ],
 "assets/menu-photos/indian-tea.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/kaddu-ki-kheer.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/karahi-chicken.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/karahi-gosht.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/kubani-ka-meeta.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/latcha-paratha.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/lukhmi.jpg": [
  1153,
  1200
 ],
 "assets/menu-photos/mango-lassi-jug.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/mango-lassi-single.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/marag.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/mirchi-ka-salan.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/mixed-grill-platter.jpg": [
  1200,
  888
 ],
 "assets/menu-photos/mixed-vegetables.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/mutton-masala.jpg": [
  1200,
  863
 ],
 "assets/menu-photos/naan-burger-combo.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/navratan-korma.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/palak-paneer.jpg": [
  929,
  1200
 ],
 "assets/menu-photos/paratha.jpg": [
  1200,
  876
 ],
 "assets/menu-photos/patthar-ka-gosht.jpg": [
  1200,
  853
 ],
 "assets/menu-photos/plain-rice.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/regular-naan.jpg": [
  1200,
  866
 ],
 "assets/menu-photos/regular-platter-chicken.jpg": [
  1200,
  900
 ],
 "assets/menu-photos/salaam-drink.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/salad.jpg": [
  1200,
  882
 ],
 "assets/menu-photos/samosa.jpg": [
  861,
  1200
 ],
 "assets/menu-photos/sitaphal-rabdi.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/tandoori-roti.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/thumbs-up.jpg": [
  1200,
  1164
 ],
 "assets/menu-photos/tilapia-fish-fry-or-grill.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/vegetable-samosa.jpg": [
  899,
  1200
 ],
 "assets/menu-photos/vegetarian-khorma.jpg": [
  1200,
  899
 ],
 "assets/menu-photos/water-bottle.jpg": [
  928,
  1200
 ],
 "assets/menu-photos/zafrani-mutton.jpg": [
  1200,
  899
 ]
};

// The only pids the site will mark vegetarian. Derived from the app's
// authoritative lib/menu-data.ts and re-checked against each dish's own
// description, so an item whose copy mentions meat is excluded no matter what
// the flag says.
export const VEGETARIAN_PIDS = new Set([
 "badam-ki-kheer|badam-ki-kheer-standard",
 "bhendi-masala|bhendi-masala-standard",
 "butter-naan|butter-naan-standard",
 "butter-paneer|butter-paneer-standard",
 "chana-masala|chana-masala-standard",
 "chapati|chapati-standard",
 "dal-tadka|dal-tadka-standard",
 "double-ka-meeta|double-ka-meeta-standard",
 "fries|fries-medium",
 "gajar-halwa|gajar-halwa-standard",
 "garlic-naan|garlic-naan-standard",
 "gulab-jamun|gulab-jamun-standard",
 "indian-tea|indian-tea-large",
 "indian-tea|indian-tea-small",
 "jeera-drink|jeera-drink-standard",
 "kaddu-ki-kheer|kaddu-ki-kheer-standard",
 "kubani-ka-meeta|kubani-ka-meeta-standard",
 "latcha-paratha|latcha-paratha-standard",
 "mango-lassi-jug|mango-lassi-jug-standard",
 "mango-lassi-single|mango-lassi-single-standard",
 "mirchi-ka-salan|mirchi-ka-salan-standard",
 "mixed-vegetables|mixed-vegetables-standard",
 "navratan-korma|navratan-korma-standard",
 "palak-paneer|palak-paneer-standard",
 "paratha|paratha-standard",
 "plain-rice|plain-rice-standard",
 "rasmalai|rasmalai-standard",
 "regular-naan|regular-naan-standard",
 "salaam-drink|salaam-drink-standard",
 "salad|salad-12oz",
 "sitaphal-rabdi|sitaphal-rabdi-standard",
 "tandoori-roti|tandoori-roti-standard",
 "thumbs-up|thumbs-up-standard",
 "veg-dum-biryani|family",
 "veg-dum-biryani|jumbo",
 "veg-dum-biryani|regular",
 "vegetable-samosa-2pc|vegetable-samosa-2pc-standard",
 "vegetable-spring-roll-6pc|vegetable-spring-roll-6pc-standard",
 "vegetarian-khorma|vegetarian-khorma-standard",
 "water-bottle|water-bottle-standard"
]);

// The owner's Signature dishes, keyed by the ITEM half of the pid so every pack
// size of one dish counts as the same dish. This is the whole answer: the menu
// manager's free-text "Signature" badge is ignored by the renderer, because two
// editable lists is how they came to disagree in the first place.
export const SIGNATURE_ITEM_IDS = new Set([
 "chicken-tikka-masala",
 "goat-dum-biryani",
 "golden-shaahi-platter",
 "mixed-grill-platter",
 "sitaphal-rabdi"
]);
