-- Catering menu (by the tray), as an orderable category on the website.
--
-- Generated from the app's lib/catering-data.ts so the two surfaces can't
-- drift; every price here also exists in create-payment-intent/prices.ts,
-- and create-web-order re-prices each line from this table at checkout.
--
-- One row per pan size (pid `cat-<dish>|half` / `|full`). web_menu_items.name
-- is UNIQUE, so the size is part of the row name; the shared `display` is the
-- dish name, and render-menu.js pairs the rows on the dish half of the pid
-- into a single menu line with a Half Tray / Full Tray picker.
--
-- Fruit Custard is deliberately half-pan only (no full row).

INSERT INTO public.web_menu_categories (code, label, sort, note)
VALUES ('ctg', 'Catering', 125,
  'Trays are cooked to order — please allow at least 4 hours, or order a day ahead. A full tray of biryani serves about 12–15 on its own, or 20+ alongside a few other trays. Online orders can include up to 2 full trays and 4 half trays; for larger events call (469) 960-3300 at least 4–5 days in advance.')
ON CONFLICT (code) DO UPDATE SET label = EXCLUDED.label, sort = EXCLUDED.sort, note = EXCLUDED.note;

-- Replaced wholesale so re-running is safe. The pids are unchanged, so
-- the two biryani bestseller cards pointing at cat-*|half/full still resolve.
DELETE FROM public.web_menu_items WHERE pid LIKE 'cat-%' OR category IN ('ctr','ctg');

INSERT INTO public.web_menu_items (kind, category, sort, name, display, note, price, published_price, pid, available) VALUES
  ('subhead','ctg',2000,'Biryani (Catering)','Biryani',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2010,'Goat Dum Biryani Half Tray','Goat Dum Biryani','Check availability with staff',95.0,95.0,'cat-goat-dum-biryani|half',true),
  ('item','ctg',2011,'Goat Dum Biryani Full Tray','Goat Dum Biryani','Check availability with staff',190.0,190.0,'cat-goat-dum-biryani|full',true),
  ('item','ctg',2021,'Chicken Dum ki Biryani Half Tray','Chicken Dum ki Biryani',NULL,70.0,70.0,'cat-chicken-dum-ki-biryani|half',true),
  ('item','ctg',2022,'Chicken Dum ki Biryani Full Tray','Chicken Dum ki Biryani',NULL,140.0,140.0,'cat-chicken-dum-ki-biryani|full',true),
  ('item','ctg',2032,'Veg Dum Biryani Half Tray','Veg Dum Biryani',NULL,65.0,65.0,'cat-veg-dum-biryani|half',true),
  ('item','ctg',2033,'Veg Dum Biryani Full Tray','Veg Dum Biryani',NULL,130.0,130.0,'cat-veg-dum-biryani|full',true),
  ('subhead','ctg',2043,'Lamb / Goat (Catering)','Lamb / Goat',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2053,'Lagan Gosth Half Tray','Lagan Gosth',NULL,95.0,95.0,'cat-lagan-gosth|half',true),
  ('item','ctg',2054,'Lagan Gosth Full Tray','Lagan Gosth',NULL,190.0,190.0,'cat-lagan-gosth|full',true),
  ('item','ctg',2064,'Dum Ka Gosht Half Tray','Dum Ka Gosht',NULL,95.0,95.0,'cat-dum-ka-gosht|half',true),
  ('item','ctg',2065,'Dum Ka Gosht Full Tray','Dum Ka Gosht',NULL,190.0,190.0,'cat-dum-ka-gosht|full',true),
  ('item','ctg',2075,'Mutton Khorma Half Tray','Mutton Khorma',NULL,95.0,95.0,'cat-mutton-khorma|half',true),
  ('item','ctg',2076,'Mutton Khorma Full Tray','Mutton Khorma',NULL,190.0,190.0,'cat-mutton-khorma|full',true),
  ('item','ctg',2086,'Kali Mirch Gosht Half Tray','Kali Mirch Gosht',NULL,95.0,95.0,'cat-kali-mirch-gosht|half',true),
  ('item','ctg',2087,'Kali Mirch Gosht Full Tray','Kali Mirch Gosht',NULL,190.0,190.0,'cat-kali-mirch-gosht|full',true),
  ('item','ctg',2097,'Kadai Gosht Half Tray','Kadai Gosht',NULL,95.0,95.0,'cat-kadai-gosht|half',true),
  ('item','ctg',2098,'Kadai Gosht Full Tray','Kadai Gosht',NULL,190.0,190.0,'cat-kadai-gosht|full',true),
  ('item','ctg',2108,'Handi Gosht Half Tray','Handi Gosht',NULL,95.0,95.0,'cat-handi-gosht|half',true),
  ('item','ctg',2109,'Handi Gosht Full Tray','Handi Gosht',NULL,190.0,190.0,'cat-handi-gosht|full',true),
  ('item','ctg',2119,'Marag Half Tray','Marag',NULL,100.0,100.0,'cat-marag|half',true),
  ('item','ctg',2120,'Marag Full Tray','Marag',NULL,200.0,200.0,'cat-marag|full',true),
  ('item','ctg',2130,'Achari Gosht Half Tray','Achari Gosht',NULL,95.0,95.0,'cat-achari-gosht|half',true),
  ('item','ctg',2131,'Achari Gosht Full Tray','Achari Gosht',NULL,190.0,190.0,'cat-achari-gosht|full',true),
  ('item','ctg',2141,'Zafrani Mutton Half Tray','Zafrani Mutton',NULL,100.0,100.0,'cat-zafrani-mutton|half',true),
  ('item','ctg',2142,'Zafrani Mutton Full Tray','Zafrani Mutton',NULL,200.0,200.0,'cat-zafrani-mutton|full',true),
  ('item','ctg',2152,'Haleem Half Tray','Haleem',NULL,110.0,110.0,'cat-haleem|half',true),
  ('item','ctg',2153,'Haleem Full Tray','Haleem',NULL,220.0,220.0,'cat-haleem|full',true),
  ('subhead','ctg',2163,'Chicken (Catering)','Chicken',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2173,'Chicken Khorma Half Tray','Chicken Khorma',NULL,70.0,70.0,'cat-chicken-khorma|half',true),
  ('item','ctg',2174,'Chicken Khorma Full Tray','Chicken Khorma',NULL,140.0,140.0,'cat-chicken-khorma|full',true),
  ('item','ctg',2184,'Kadai Chicken Half Tray','Kadai Chicken',NULL,70.0,70.0,'cat-kadai-chicken|half',true),
  ('item','ctg',2185,'Kadai Chicken Full Tray','Kadai Chicken',NULL,140.0,140.0,'cat-kadai-chicken|full',true),
  ('item','ctg',2195,'Dum Ka Chicken Half Tray','Dum Ka Chicken',NULL,70.0,70.0,'cat-dum-ka-chicken|half',true),
  ('item','ctg',2196,'Dum Ka Chicken Full Tray','Dum Ka Chicken',NULL,140.0,140.0,'cat-dum-ka-chicken|full',true),
  ('item','ctg',2206,'Lagan Chicken Half Tray','Lagan Chicken',NULL,70.0,70.0,'cat-lagan-chicken|half',true),
  ('item','ctg',2207,'Lagan Chicken Full Tray','Lagan Chicken',NULL,140.0,140.0,'cat-lagan-chicken|full',true),
  ('item','ctg',2217,'Butter Chicken Half Tray','Butter Chicken',NULL,80.0,80.0,'cat-butter-chicken|half',true),
  ('item','ctg',2218,'Butter Chicken Full Tray','Butter Chicken',NULL,160.0,160.0,'cat-butter-chicken|full',true),
  ('item','ctg',2228,'Chicken 65 Half Tray','Chicken 65',NULL,80.0,80.0,'cat-chicken-65|half',true),
  ('item','ctg',2229,'Chicken 65 Full Tray','Chicken 65',NULL,160.0,160.0,'cat-chicken-65|full',true),
  ('item','ctg',2239,'Chilli Chicken Half Tray','Chilli Chicken',NULL,80.0,80.0,'cat-chilli-chicken|half',true),
  ('item','ctg',2240,'Chilli Chicken Full Tray','Chilli Chicken',NULL,160.0,160.0,'cat-chilli-chicken|full',true),
  ('item','ctg',2250,'Frontier Chicken Half Tray','Frontier Chicken',NULL,80.0,80.0,'cat-frontier-chicken|half',true),
  ('item','ctg',2251,'Frontier Chicken Full Tray','Frontier Chicken',NULL,160.0,160.0,'cat-frontier-chicken|full',true),
  ('subhead','ctg',2261,'Grill / Kabab (Catering)','Grill / Kabab',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2271,'Chicken Sheek Kabab Half Tray','Chicken Sheek Kabab',NULL,80.0,80.0,'cat-chicken-sheek-kabab|half',true),
  ('item','ctg',2272,'Chicken Sheek Kabab Full Tray','Chicken Sheek Kabab',NULL,160.0,160.0,'cat-chicken-sheek-kabab|full',true),
  ('item','ctg',2282,'Beef Sheek Kabab Half Tray','Beef Sheek Kabab',NULL,85.0,85.0,'cat-beef-sheek-kabab|half',true),
  ('item','ctg',2283,'Beef Sheek Kabab Full Tray','Beef Sheek Kabab',NULL,175.0,175.0,'cat-beef-sheek-kabab|full',true),
  ('item','ctg',2293,'Chicken Chapli Kabab Half Tray','Chicken Chapli Kabab',NULL,80.0,80.0,'cat-chicken-chapli-kabab|half',true),
  ('item','ctg',2294,'Chicken Chapli Kabab Full Tray','Chicken Chapli Kabab',NULL,160.0,160.0,'cat-chicken-chapli-kabab|full',true),
  ('item','ctg',2304,'Beef Chapli Kabab Half Tray','Beef Chapli Kabab',NULL,85.0,85.0,'cat-beef-chapli-kabab|half',true),
  ('item','ctg',2305,'Beef Chapli Kabab Full Tray','Beef Chapli Kabab',NULL,175.0,175.0,'cat-beef-chapli-kabab|full',true),
  ('item','ctg',2315,'Chicken Tikka Half Tray','Chicken Tikka',NULL,80.0,80.0,'cat-chicken-tikka|half',true),
  ('item','ctg',2316,'Chicken Tikka Full Tray','Chicken Tikka',NULL,160.0,160.0,'cat-chicken-tikka|full',true),
  ('item','ctg',2326,'Chicken Malai Boti Half Tray','Chicken Malai Boti',NULL,80.0,80.0,'cat-chicken-malai-boti|half',true),
  ('item','ctg',2327,'Chicken Malai Boti Full Tray','Chicken Malai Boti',NULL,160.0,160.0,'cat-chicken-malai-boti|full',true),
  ('item','ctg',2337,'Bihari Kabab Half Tray','Bihari Kabab',NULL,110.0,110.0,'cat-bihari-kabab|half',true),
  ('item','ctg',2338,'Bihari Kabab Full Tray','Bihari Kabab',NULL,220.0,220.0,'cat-bihari-kabab|full',true),
  ('subhead','ctg',2348,'Vegetarian (Catering)','Vegetarian',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2358,'Dalcha Half Tray','Dalcha',NULL,80.0,80.0,'cat-dalcha|half',true),
  ('item','ctg',2359,'Dalcha Full Tray','Dalcha',NULL,160.0,160.0,'cat-dalcha|full',true),
  ('item','ctg',2369,'Palak Paneer Half Tray','Palak Paneer',NULL,60.0,60.0,'cat-palak-paneer|half',true),
  ('item','ctg',2370,'Palak Paneer Full Tray','Palak Paneer',NULL,120.0,120.0,'cat-palak-paneer|full',true),
  ('item','ctg',2380,'Butter Paneer Half Tray','Butter Paneer',NULL,80.0,80.0,'cat-butter-paneer|half',true),
  ('item','ctg',2381,'Butter Paneer Full Tray','Butter Paneer',NULL,160.0,160.0,'cat-butter-paneer|full',true),
  ('item','ctg',2391,'Mixed Veg Half Tray','Mixed Veg',NULL,60.0,60.0,'cat-mixed-veg|half',true),
  ('item','ctg',2392,'Mixed Veg Full Tray','Mixed Veg',NULL,120.0,120.0,'cat-mixed-veg|full',true),
  ('item','ctg',2402,'Khorma Half Tray','Khorma',NULL,60.0,60.0,'cat-veg-khorma|half',true),
  ('item','ctg',2403,'Khorma Full Tray','Khorma',NULL,120.0,120.0,'cat-veg-khorma|full',true),
  ('item','ctg',2413,'Bhendi Masala Half Tray','Bhendi Masala',NULL,60.0,60.0,'cat-bhendi-masala|half',true),
  ('item','ctg',2414,'Bhendi Masala Full Tray','Bhendi Masala',NULL,120.0,120.0,'cat-bhendi-masala|full',true),
  ('item','ctg',2424,'Chana Masala Half Tray','Chana Masala',NULL,55.0,55.0,'cat-chana-masala|half',true),
  ('item','ctg',2425,'Chana Masala Full Tray','Chana Masala',NULL,110.0,110.0,'cat-chana-masala|full',true),
  ('subhead','ctg',2435,'Fish (Catering)','Fish',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2445,'Fish Fry Half Tray','Fish Fry',NULL,80.0,80.0,'cat-fish-fry|half',true),
  ('item','ctg',2446,'Fish Fry Full Tray','Fish Fry',NULL,160.0,160.0,'cat-fish-fry|full',true),
  ('item','ctg',2456,'Apollo Fish Half Tray','Apollo Fish',NULL,80.0,80.0,'cat-apollo-fish|half',true),
  ('item','ctg',2457,'Apollo Fish Full Tray','Apollo Fish',NULL,160.0,160.0,'cat-apollo-fish|full',true),
  ('item','ctg',2467,'Lahori Fish Fry Half Tray','Lahori Fish Fry',NULL,80.0,80.0,'cat-lahori-fish-fry|half',true),
  ('item','ctg',2468,'Lahori Fish Fry Full Tray','Lahori Fish Fry',NULL,160.0,160.0,'cat-lahori-fish-fry|full',true),
  ('subhead','ctg',2478,'Beef (Catering)','Beef',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2488,'Beef Nihari Half Tray','Beef Nihari',NULL,100.0,100.0,'cat-beef-nihari|half',true),
  ('item','ctg',2489,'Beef Nihari Full Tray','Beef Nihari',NULL,200.0,200.0,'cat-beef-nihari|full',true),
  ('item','ctg',2499,'Beef Fry Half Tray','Beef Fry',NULL,95.0,95.0,'cat-beef-fry|half',true),
  ('item','ctg',2500,'Beef Fry Full Tray','Beef Fry',NULL,190.0,190.0,'cat-beef-fry|full',true),
  ('item','ctg',2510,'Frontier Beef Half Tray','Frontier Beef',NULL,95.0,95.0,'cat-frontier-beef|half',true),
  ('item','ctg',2511,'Frontier Beef Full Tray','Frontier Beef',NULL,190.0,190.0,'cat-frontier-beef|full',true),
  ('subhead','ctg',2521,'Dessert (Catering)','Dessert',NULL,NULL,NULL,NULL,true),
  ('item','ctg',2531,'Fruit Custard Half Tray','Fruit Custard',NULL,70.0,70.0,'cat-fruit-custard|half',true),
  ('item','ctg',2541,'Badam Kheer Half Tray','Badam Kheer',NULL,80.0,80.0,'cat-badam-kheer|half',true),
  ('item','ctg',2542,'Badam Kheer Full Tray','Badam Kheer',NULL,160.0,160.0,'cat-badam-kheer|full',true),
  ('item','ctg',2552,'Khubani Ka Meeta Half Tray','Khubani Ka Meeta',NULL,70.0,70.0,'cat-khubani-ka-meeta|half',true),
  ('item','ctg',2553,'Khubani Ka Meeta Full Tray','Khubani Ka Meeta',NULL,150.0,150.0,'cat-khubani-ka-meeta|full',true),
  ('item','ctg',2563,'Truffle Pudding Half Tray','Truffle Pudding',NULL,75.0,75.0,'cat-truffle-pudding|half',true),
  ('item','ctg',2564,'Truffle Pudding Full Tray','Truffle Pudding',NULL,150.0,150.0,'cat-truffle-pudding|full',true),
  ('item','ctg',2574,'Double Ka Meeta Half Tray','Double Ka Meeta',NULL,50.0,50.0,'cat-double-ka-meeta|half',true),
  ('item','ctg',2575,'Double Ka Meeta Full Tray','Double Ka Meeta',NULL,100.0,100.0,'cat-double-ka-meeta|full',true),
  ('item','ctg',2585,'Kaddu Ki Kheer Half Tray','Kaddu Ki Kheer',NULL,70.0,70.0,'cat-kaddu-ki-kheer|half',true),
  ('item','ctg',2586,'Kaddu Ki Kheer Full Tray','Kaddu Ki Kheer',NULL,140.0,140.0,'cat-kaddu-ki-kheer|full',true),
  ('item','ctg',2596,'Apricot Delight Half Tray','Apricot Delight',NULL,80.0,80.0,'cat-apricot-delight|half',true),
  ('item','ctg',2597,'Apricot Delight Full Tray','Apricot Delight',NULL,160.0,160.0,'cat-apricot-delight|full',true),
  ('item','ctg',2607,'Badam Ka Kund Half Tray','Badam Ka Kund',NULL,85.0,85.0,'cat-badam-ka-kund|half',true),
  ('item','ctg',2608,'Badam Ka Kund Full Tray','Badam Ka Kund',NULL,170.0,170.0,'cat-badam-ka-kund|full',true),
  ('item','ctg',2618,'Cream Fruit with Ice Cream Half Tray','Cream Fruit with Ice Cream',NULL,85.0,85.0,'cat-cream-fruit-ice-cream|half',true),
  ('item','ctg',2619,'Cream Fruit with Ice Cream Full Tray','Cream Fruit with Ice Cream',NULL,170.0,170.0,'cat-cream-fruit-ice-cream|full',true);
